version: "3.9"

services:
  django_host:
    image: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/company
    ports:
     - 8000:8000
    depends_on:
      - redis
      - migration
  migration:
    image: migrate
    build:
      context: .
      dockerfile: Dockerfile.migrations
    volumes:
    - .:/company

  redis:
    image: redis
    ports:
    - 6379:6379
